version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - toolbox-deploy:
          filters:
            branches:
              only: "/(master|staging)/"
            tags:
              ignore: "/.*/"
          context: challenge-toolbox

executors:
  toolbox-executor:
    docker:
      - image: eu.gcr.io/${GOOGLE_PROJECT_ID}/challenge-toolbox:v3
        auth:
          username: "${DOCKER_LOGIN_GCR_EU_USERNAME}"
          password: "${DOCKER_LOGIN_GCR_EU_PASSWORD}"

jobs:
  toolbox-deploy:
    executor: toolbox-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Deploy with challenge-toolbox
          command: >-
            entrypoint.sh
            deploy.py
            "${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"
            "${CIRCLE_PROJECT_REPONAME}"
            "${CIRCLE_BRANCH}"
